import {
  AdminApiResponse,
  PermissionsApiResponse,
  createAdminResponseT,
  createAdminT,
  updateAdminT,
} from "@/types/types";
import { appApi } from "@/redux/services/appApi";
import { DEFAULT_PER_PAGE } from "@/lib/constants";

export const adminsApiSlice = appApi.injectEndpoints({
  endpoints: (build) => ({
    getAllAdmins: build.query<
      AdminApiResponse,
      { page: number; perPage?: number; status?: string; search?: string }
    >({
      query: ({ page, perPage = DEFAULT_PER_PAGE, search }) => {
        const params = new URLSearchParams({
          page: page.toString(),
          per_page: perPage.toString(),
        });

        if (search) {
          params.append("search", search);
        }

        return `all?${params.toString()}`;
      },
      transformResponse: (response: AdminApiResponse) => response,
      providesTags: () => [{ type: "adminApi" }],
    }),
    saveAdmin: build.mutation<createAdminResponseT, createAdminT>({
      query: (admin: createAdminT) => ({
        url: ``,
        method: "POST",
        body: admin,
      }),
      transformResponse: (response: createAdminResponseT) => {
        console.log("Response rtk", response);
        return response;
      },
      invalidatesTags: (_result, error) => (!error ? ["adminApi"] : ["rolesApi"]),
    }),
    updateAdmin: build.mutation<createAdminResponseT, updateAdminT>({
      query: (admin: updateAdminT) => ({
        url: `${admin.id}`,
        method: "PUT",
        body: admin,
      }),
      transformResponse: (response: createAdminResponseT) => {
        return response;
      },
      invalidatesTags: () => ["adminApi"],
    }),
    toggleAdmin: build.mutation<updateAdminT, { adminId: number; deactivate: boolean }>({
      query: ({ adminId, deactivate }) => ({
        url: `${adminId}/toggle-status`,
        method: "PATCH",
        body: { deactivate },
      }),
      invalidatesTags: () => ["adminApi"],
    }),

    getPermissions: build.query<PermissionsApiResponse, { page?: number; perPage?: number }>({
      query: ({ page = 1, perPage = 10 } = {}) => `permissions?page=${page}&per_page=${perPage}`,
      transformResponse: (response: PermissionsApiResponse) => response,
      providesTags: () => [{ type: "permissionsApi" }],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
//console.log('TodosApiSlice ',todosApiSlice)
export const {
  useGetAllAdminsQuery,
  useGetPermissionsQuery,
  useSaveAdminMutation,
  useUpdateAdminMutation,
  useToggleAdminMutation,
} = adminsApiSlice;
